### ISSUE TITLE
Mark fields as required

### ISSUE THREAD

**Issue by sk-** [plaid/plaid-openapi#10]
It seems that all the api endpoints always include all the fields in their responses, and in case no value is set for a given field `null` is used to denote that. In fact the typescript definition files show that. However, not all fields are marked as required in the OpenApi responses.

For example `JWKPublicKey` has no required fields in the spec, but all fields are required in the typescript definitions. Similar things happen to `Holdings` or `Securities`.

**Comment by cgfarmer4** [comment]
hi @sk- 

>It seems that all the api endpoints always include all the fields in their responses

This is not quite true and we've indicated `nullable` where this can happen. 

> but all fields are required in the typescript definitions

Can you point to the `typescript` definitions mentioned? What generator are you using?

**Comment by cgfarmer4** [comment]
We try to add `required` where the responses are guaranteed. And when using the `typescript-axios` generator with OpenAPI generator this behavior is correct as non `required` keys come back as optionals.

**Comment by sk-** [comment]
@cgfarmer Please quote the whole sentences when replying. I understand that the fields are not always defined with a meaningful value, but in such cases your API returns null, rather than not setting the field (making them optionals), and that's what this whole issue is about.

Look for example at [`WebhookVerificationKeyResponse`](https://github.com/plaid/plaid-node/blob/e096577ea9351509cd23dca33564643f2fa6436d/index.d.ts#L773-L785) and compare it to [`JWKPublicKey`](https://github.com/plaid/plaid-openapi/blob/b67d577b12051fb5e6d584a76ae97f6ea5de2f85/2020-09-14.yml#L4477-L4506). Look how none of the fields are required in the OpenAPI spec, but all are int the previous TS definitions.

I think there's a misunderstanding about `nullable`. That property by itself does not make the field required. Check for example [`Security`](https://github.com/plaid/plaid-openapi/blob/b67d577b12051fb5e6d584a76ae97f6ea5de2f85/2020-09-14.yml#L9014-L9098), in which all fields are nullable except for `type`, `security_id` and `is_cash_equivalent` (this latter one being optional). (Note that `type` and `is_cash_equivalent` are nullable in the [TS definitions](https://github.com/plaid/plaid-node/blob/e096577ea9351509cd23dca33564643f2fa6436d/index.d.ts#L137-L153)).

Note that not setting a nullable-field as required would generate a field like:

```ts
interface Response {
  field?: type | null;
}
```

which means that in code one needs to check for both `undefined` and `null`.

**Comment by cgfarmer4** [comment]
Thanks @sk- for pointing this out. I will address

**Comment by skylarmb** [comment]
@cgfarmer4 isnt this fixed now?

**Comment by sk-** [comment]
@skylarmb no it isn't. There's only one [commit](https://github.com/plaid/plaid-openapi/commit/5a1a174d2b482d5b9bdaa31281cd7a0e2492fbd5#) after the issue was created but it doesn't address the issue.

**Comment by phoenixy1** [comment]
@sk- The latest update should fix this for the majority of cases. Please feel free to open new issues if we missed any!
