### ISSUE TITLE
Discrepancy on HealthIncident object

### ISSUE THREAD

**Issue by viceroypenguin** [plaid/plaid-openapi#106]
Currently, the `HealthIncident` object (2020-09-14.yml, L21684) indicates that the `end_date` property is not nullable. However, querying for certain institutions (specifically "ins_3", among others) returns `HealthIncident` objects with a `null` value for `end_date`. I am correcting in my library manually for now, but it would be nice to see this fixed with the next update.

See also: viceroypenguin/Going.Plaid#96

**Comment by phoenixy1** [comment]
Thanks for reporting. Will be fixed in next month's release!
