### ISSUE TITLE
AddressMatchScore title

### ISSUE THREAD

**Issue by viceroypenguin** [plaid/plaid-openapi#114]
Currently, the `AddressMatchScore` entity has a `title` of `address`. I have been using `title` when present to parse the entity names, due to some types having unusable entity names. Specifically, in this case, the `address` title seems out of place, and is creating a conflict with the `Address` entity. 

Would it be possible to either delete the `title` or set it to a more appropriate value? Thanks.

re: viceroypenguin/Going.Plaid#113

**Comment by phoenixy1** [comment]
@viceroypenguin sure, that seems like a reasonable enough ask. I have just submitted a PR and, absent any unexpected surprises, this should go out in the next client library release.

**Comment by viceroypenguin** [comment]
Thank you! :)
