### ISSUE TITLE
dates, datetimes, tooling

### ISSUE THREAD

**Issue by Lewiscowles1986** [plaid/plaid-openapi#122]
👋  It looks like your dates and date-time entries are subtly breaking a tool I use `json-schema-faker` when used with `JSONSchemaFaker.option({ useExamplesValue: true, useDefaultValue: true });`

This is for two reasons I can tell

1. `datetime` being set where something should be `date` (at least according to [openapi 3 spec at swagger.io](https://swagger.io/docs/specification/data-models/data-types/#string))
2. `date-time` (correct OAS3 👍 ) having a "zulu-character terminated string" format without a `.` (this could well be a `json-schema-faker` support problem, as the example given in OpenAPI swagger 3 spec is `2017-07-21T17:32:28Z` which does match your format.

**Comment by Lewiscowles1986** [comment]
Proposed fix MR for the Z string on `date-time`, should solve [2] https://github.com/json-schema-faker/json-schema-faker/pull/765

**Comment by Lewiscowles1986** [comment]
Also a one-liner to fix this spec to comply with the example-given, and description too.

**Comment by phoenixy1** [comment]
thanks!! Like I mentioned on the PR I've submitted a fix for this internally, it will be released here next month.

**Comment by Lewiscowles1986** [comment]
👍
