### ISSUE TITLE
Invalid yaml

### ISSUE THREAD

**Issue by Lewiscowles1986** [plaid/plaid-openapi#124]
- `/income/verification/documents/download`
- `/beta/credit/v1/bank_employment/get`
- `/deposit_switch/get`

All have API errors in their yaml

most can be fixed with indentation; the beta one has `x-hidden-from-docs: true` outside of a method, which means some tooling treats it as a method and crashes.

**Comment by phoenixy1** [comment]
We validate the OpenAPI file using the validator at https://apitools.dev/swagger-parser/online/ and it passes that validation. If there is a specific different validation tool that you are running or specific places where you think the indentation should be changed, please let us know.

**Comment by Lewiscowles1986** [comment]
Okay so for `/deposit_switch/get` and `/income/verification/documents/download` would you say that parameters is correctly indented, or indeed necesarry?

Even within the same file, the indentation is different to all the other endpoints featuring `parameters: []`

`/beta/credit/v1/bank_employment/get` has an `x-hidden-from-docs: true` which is not within a http method under a path. Is that correct?

I don't doubt you have automation. These endpoints are documented, but don't seem to work with http://json-schema-faker.js.org when passed through https://apitools.dev/swagger-parser/ being told to use examples.

Also when I try to use these endpoints using swagger generator I get errors like the following

```
{
    "message": "unknown format \"datetime\" is used in schema at path \"#/properties/initiated_date\""
}
```

which is a http 500 error.

**Comment by Lewiscowles1986** [comment]
Other tooling used (problematically) are things like postman

<img width="1372" alt="Screenshot 2023-05-16 at 01 13 18" src="https://github.com/plaid/plaid-openapi/assets/2605791/3046906f-fd94-4a66-8df2-cc6a0b2ab5d5">

The correct body is 

```
{
  "user_token": "{{userToken}}",
  "client_id": "{{clientId}}",
  "secret": "{{clientSecret}}"
}
```

not

```
{
  "user_token": {
    "value": "<Error: Too many levels of nesting to fake this schema>"
  },
  "client_id": {
    "value": "<Error: Too many levels of nesting to fake this schema>"
  },
  "secret": {
    "value": "<Error: Too many levels of nesting to fake this schema>"
  }
}
```

which is what happens if I try to import `https://raw.githubusercontent.com/plaid/plaid-openapi/7e49c5e145b894913c257cc3eaf2354b48245909/2020-09-14.yml` (currently `master`)

**Comment by Lewiscowles1986** [comment]
None of this is intended to be problematic. When I asked about OpenAPI2 support, I accepted that OAS3 is what we should work with. I Also accept this is difficult and new and a hard area and that PR's are not really worth it, as they then need to be translated to some program that generates that file. I Just want things to work and not cause issues. Using swagger generator and verifying calls to plaid via postman are two ways of  troubleshooting that implementations in code match the API-spec contract as well as making calls direct to plaid to gain visibility.

**Comment by phoenixy1** [comment]
Thanks, that is super helpful detail.

The `x-hidden-from-docs: true` I can fix (it doesn't even do anything, so we can delete that line)
The `parameters` indentation is also an easy fix (and again, I'm not sure it's even doing anything) 
The `format: datetime` thing is something we already caught internally and it's fixed on master, so that should be rolled out with next month's release.

The Postman error seems like unfortunately a limitation in Postman rather than anything wrong with the API specification, so I don't think there's anything we can do about that. There are some suggested workarounds floating around online, e.g.: https://github.com/postmanlabs/postman-app-support/issues/10928

**Comment by Lewiscowles1986** [comment]
Super helpful thanks. The workaround I'm picking out from that little thread might be

```
openapi2postmanv2 -s root.yaml -o collection.json -p -O folderStrategy=Tags,includeAuthInfoInExample=false,optimizeConversion=false,stackLimit=50
```

I've applied the fixes locally and just did a find replace for the hyphenation of date-time; It's more that I'd sooner not write automated tools; it's not just plaid, every vendor has... insert quirky thing 👍
