### ISSUE TITLE
Generate Python library with type hints

### ISSUE THREAD

**Issue by chrisphilip322** [plaid/plaid-openapi#128]
I tried to follow the instructions in the README to run `openapi-generator-cli` to generate a python library so that I can generate a version with type hints. I ran the example codesnippet (mostly)

```
java -jar openapi-generator-cli.jar generate -g python \
-i 2020-09-14.yml \
-o build/generated-python \
-p packageName=plaid \
--global-property apiTests=false,modelTests=false \
-t templates/python
```

and a python library was generated. I tried to use this library as a replacement for the library published from https://github.com/plaid/plaid-python but the generated library didn't match the interface of the published one (and the generated library had some minor syntax errors).

The generated library does have type hints, but the differences in behavior are causing me issues; including this error when making a transactions_sync request
```
plaid.exceptions.ApiValueError: Invalid content_type returned. Content_type='application/json; charset=utf-8' was returned when only {'application/json'} are defined for status_code=200
```

Are there other flags that should be passed to the generator to get a library more compatible with the published one/a working one with type hints?

**Comment by phoenixy1** [comment]
We generate using version 6.1.0 of openapi generator, so make sure you're using the same version -- there were substantial changes to the generated python lib syntax in 6.2 and later. I assume you're also using the template in https://github.com/plaid/plaid-python/tree/master/templates/python? Let me know if you've tried both those things and it doesn't work and if so I'll dig in a bit more

**Comment by phoenixy1** [comment]
@chrisphilip322 did this resolve your issue? want to know if I should keep this open.
