### ISSUE TITLE
NumbersIBANNullable is not compiling when generating kotlin client

### ISSUE THREAD

**Issue by akhileshagarwal85** [plaid/plaid-openapi#132]
When a `kotlin plaid sdk` is generated using openapi-generator, the class NumbersIBANNullable is generated as a data class and since this class is not having any properties it results in compilation error as below,

`NumbersIBANNullable.kt: Data class must have at least one primary constructor parameter`

Since, this class is not referenced from anywhere, just removing it solves the problem. Now, I am not sure if this is how it should be solved. So, raising it here to be solved accordingly.

Below is the command used to generate the client.

```
openapi-generator generate -g kotlin \                                                                                                                         ✘ INT
-i 2020-09-14.yml \
-o build/generated-kotlin \
--library=jvm-okhttp3 \
--global-property apiDocs=false,modelDocs=false,apiTests=false,modelTests=false \
-p artifactId=plaid,apiPackage=com.plaid.client.request,modelPackage=com.plaid.client.model,dateLibrary=java8 \
-t teamplates/java \
--type-mappings=BigDecimal=Double
```

**Comment by phoenixy1** [comment]
That looks like a bug in OpenAPI generator: https://github.com/OpenAPITools/openapi-generator/issues/14710

Since NumbersIBANNullable isn't referenced (as you point out), removing it should be fine and not cause any problems.
