### ISSUE TITLE
[Python SDK]: `TransferUser` does not exist in create transfer authorization request

### ISSUE THREAD

**Issue by mdanish-kh** [plaid/plaid-openapi#176]
## Description

For transfer authorization create API https://plaid.com/docs/api/products/transfer/initiating-transfers/#transferauthorizationcreate in Python. I believe the request should be modified as

```diff
request = TransferAuthorizationCreateRequest(
    access_token='<>',
    account_id='<>',
    type=TransferType('debit'),
    network=TransferNetwork('ach'),
    amount='12.34',
-   user=TransferUser(legal_name='Anne Charleston'),
+   user=TransferAuthorizationUserInRequest(legal_name='Anne Charleston')
    ach_class=ACHClass('ppd')
)
```

I couldn't find the `TransferUser` type in the python SDK. The request works with `TransferAuthorizationUserInRequest` which is imported as `from plaid.model.transfer_authorization_user_in_request import TransferAuthorizationUserInRequest`

**Comment by phoenixy1** [comment]
@mdanish-kh thanks for reporting this! I've put it in a fix to the docs and it should be deployed by the end of the week.
