### ISSUE TITLE
Liabilities - Mortgage account_number is sometimes null

### ISSUE THREAD

**Issue by kevindice** [plaid/plaid-openapi#186]
The schema says that the `account_number` on a mortgage liability is always a string, but the documentation shows that it can be nullable.  When using the Sandbox environment, the Python client throws an error because the response comes back with a null account_number.

**Comment by phoenixy1** [comment]
Thank you for the report! Closing this as a duplicate of https://github.com/plaid/plaid-python/issues/538. Issue will be resolved in the next client library release.
