### ISSUE TITLE
Documentation Bug

### ISSUE THREAD

**Issue by viceroypenguin** [plaid/plaid-openapi#25]
Submitting as an issue rather than PR due to auto-generated .yml file.

The documentation entry [here](https://github.com/plaid/plaid-openapi/blob/6cbdf2598fb7607f5f8a67557f929308104c2d37/2020-09-14.yml#L10144) for `pop` (Point of Purchase enum value for ACHClass) has the ` and the " backwards.

**Comment by phoenixy1** [comment]
good eyes! fixing.

**Comment by phoenixy1** [comment]
fixed in latest release
