### ISSUE TITLE
Not a valid OpenAPI 3.0 Specification

### ISSUE THREAD

**Issue by relsunkaev** [plaid/plaid-openapi#29]
I could not parse this spec using [prance](https://github.com/RonnyPfannschmidt/prance) with the [OpenAPI Spec Validator](https://github.com/p1c2u/openapi-spec-validator) back end. IBM's [OpenAPI Validator](https://github.com/IBM/openapi-validator#warnings-limit) throws up 99 errors and 312 warnings as well (for obvious reasons I won't list them all here).

**Comment by phoenixy1** [comment]
Thanks for reporting this!

We currently lint the file using the default Spectral ruleset included with Stoplight, and the latest version (which may not be the version pushed publicly) has zero errors according to that ruleset. 

The OpenAPI validator used by IBM is quite opinionated and throws a number of errors in response to patterns that do not violate the OpenAPI spec. I'll run through the errors and will fix any that seem to be legitimate, but getting the IBM OpenAPI validator to report zero errors when run with its default ruleset is probably a non-goal of the project.

**Comment by shekita88** [comment]
#27 #28 #25

**Comment by phoenixy1** [comment]
I ran the openapi validator and the one issue it surfaced that I think was unambiguously legitimate was that payment_id was part of the spec but missing from the example -- I fixed that. The other issues to me seemed like style issues or false positives. Please go ahead and open a new ticket if there are other validation issues you'd want to see fixed.
