### ISSUE TITLE
Enum Value bug

### ISSUE THREAD

**Issue by viceroypenguin** [plaid/plaid-openapi#31]
[link](https://github.com/plaid/plaid-openapi/blob/a6240ba8f17414095fa643be1b8f3a9e09699252/2020-09-14.yml#L9337) The value here has an extra tab by accident.  "non-taxable brokerage account\t"

**Comment by phoenixy1** [comment]
eep! fixing now, should have the release hopefully next week.

**Comment by phoenixy1** [comment]
...not going to be next week as I'm packaging it with the fix to #10 which is turning out to be pretty hairy. But soon!

**Comment by phoenixy1** [comment]
should be resolved with the latest merge
