### ISSUE TITLE
Sharing Your OpenAPI Story

### ISSUE THREAD

**Issue by kinlane** [plaid/plaid-openapi#4]
Hello there. I'd love to work with y'all to share your OpenAPI story as part of the OpenAPI Initiative (OAI) - https://www.openapis.org/ -- ping me if interested.

**Comment by cgfarmer4** [comment]
cc @phoenixy1

**Comment by phoenixy1** [comment]
@kinlane yes, we would be happy to chat.  What would be the best next steps?
