### ISSUE TITLE
Incorrect title correction

### ISSUE THREAD

**Issue by viceroypenguin** [plaid/plaid-openapi#42]
The `title` property of these objects is blank. Removing these properties would be more accurate in these places.

https://github.com/plaid/plaid-openapi/blob/e19f479432f38507a4f0dd83e71755b4a23ab685/2020-09-14.yml#L4481
https://github.com/plaid/plaid-openapi/blob/e19f479432f38507a4f0dd83e71755b4a23ab685/2020-09-14.yml#L5019
https://github.com/plaid/plaid-openapi/blob/e19f479432f38507a4f0dd83e71755b4a23ab685/2020-09-14.yml#L8674

**Comment by viceroypenguin** [comment]
Also, `PaymentMeta` has a `title` that refers to a different name than the type, unlike all of the other types. 

https://github.com/plaid/plaid-openapi/blob/e19f479432f38507a4f0dd83e71755b4a23ab685/2020-09-14.yml#L7233-7234

**Comment by phoenixy1** [comment]
in progress!

**Comment by viceroypenguin** [comment]
Thanks!!
