### ISSUE TITLE
Date/Time field identification

### ISSUE THREAD

**Issue by viceroypenguin** [plaid/plaid-openapi#43]
For strong-typing fields, it is useful to identify which ones are date/datetime. However, I have found 5 ways to identify a datetime field and one for date fields, and one that is ambiguous, but seems to be generally datetime:

#### DateTime
* If the `format` is `date-time`
* If the `description` contains `2020-10-30T15:26:48Z`
* If the `description` contains `2018-04-12T03:32:11Z`
* If the `description` contains `2017-09-14T14:42:19.350Z`
* If the `description` contains `YYYY-MM-DDTHH:mm:ssZ`

#### Date
* If the `description` contains `yyyy-mm-dd` / `YYYY-MM-DD` (but not `THH:mm:ssZ`)

#### Technically ambiguous
* If the `description` contains `ISO 8601`, but none of the above strings as well. 

Request: to have consistency in these fields, to identify all of them either by the `format` or by `YYYY-MM-DD` (or both). I can provide a list of object/fields to make your jobs easier if needed.

**Comment by phoenixy1** [comment]
in progress!

**Comment by viceroypenguin** [comment]
Thanks!!

**Comment by viceroypenguin** [comment]
@phoenixy1 These items are not yet marked correctly, FYI:
* `DepositSwitchTokenCreateResponse.deposit_switch_token_expiration_time`
* `ConnectedApplication.created_at`

**Comment by phoenixy1** [comment]
Yeah -- the deposit switch change broke some tests and given this: https://www.protocol.com/fintech/plaid-payroll-data-deposit-switch it didn't seem worth fixing.

ConnectedApplication.created_at we didn't change right now because it's a PX specific endpoint and we don't really expect PX developers to use these libraries, tho I can double check with the PX team on that thought.

**Comment by viceroypenguin** [comment]
Fair enough - if there's reasons for them not to be marked correctly, I'm good with that. Thanks!

**Comment by viceroypenguin** [comment]
@phoenixy1 Apologies, but bug report. One field marked incorrectly: LinkTokenCreateRequestUser.date_of_birth

**Comment by phoenixy1** [comment]
eep, good catch. will be fixed in next release.

**Comment by phoenixy1** [comment]
should be fixed by today's release.
