### ISSUE TITLE
InvestmentAccountSubtype contains an integer 529 in it's enumerated values

### ISSUE THREAD

**Issue by ahl** [plaid/plaid-openapi#89]
Several types include the string "529", but `InvestmentAccountSubtype` omits the quotes so 529 is interpreted as an integer. This is technically incompatible with the string type.

**Comment by phoenixy1** [comment]
I don't know how I missed this issue but -- ugh! Fixing it RIGHT NOW. Will be updated in the September OpenAPI release. Thank you for reporting.
